name: build docs

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
      - "mkdocs.yml"

permissions:
  contents: write
jobs:
  deploy:
    # if: startsWith(github.ref, 'refs/tags/') # only deploy pages on release tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Deploy to mode-s.org/jet1090
        run: |
          git ls-remote "https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/open-aviation/jet1090"
          git remote rm origin
          git remote add origin "https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/open-aviation/jet1090"
          uvx --with "mkdocs-material[imaging]" mkdocs gh-deploy --force
